apiVersion: v1
kind: Service
metadata:
  name: workflow
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 23000
  selector:
    app: workflow
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
      - name: workflow
        image: 172.29.0.13:8082/workflow:<BUILD_TAG>
        imagePullPolicy: Always
        volumeMounts:
        - name: time-zone
          mountPath: /etc/localtime
        - name: tomcat-logs
          mountPath: /usr/local/tomcat/logs
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: time-zone
        hostPath:
          path: /etc/localtime
      - name: tomcat-logs
        hostPath:
          path: /data/tomcat/logs